name:                e1-268H
version:             0.1.0.0
github:              "edilmedeiros/dcpu16-emulator-hs"
license:             BSD3
author:              "Edil Medeiros"
maintainer:          "jose.edil@gmail.com"
copyright:           "2023 Edil Medeiros"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            emulator

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/edilmedeiros/dcpu16-emulator-hs#readme>

dependencies:
- base >= 4.7 && < 5
- vector >= 0.13 && < 0.14
- bytestring >= 0.11.5 && < 0.11.6
- text >= 2.0 && < 2.1
- text-show >= 3.10.0 && < 3.11.0
- mtl >= 2.2 && < 2.3
- microlens >= 0.4.13 && < 0.4.14
- microlens-th >= 0.4.3 && < 0.4.4
# - microlens-mtl >= 0.2.0 && < 0.2.1
# - microlens-platform >= 0.4.3 && < 0.4.4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  e1-268H:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - e1-268H

tests:
  e1-268H-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - e1-268H
