name:                dcpu16-emulator-hs
version:             0.1.0.0
github:              "edilmedeiros/dcpu16-emulator-hs"
license:             BSD3
author:              "Edil Medeiros"
maintainer:          "jose.edil@gmail.com"
copyright:           "2023 Edil Medeiros"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            emulator

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/edilmedeiros/dcpu16-emulator-hs#readme>

dependencies:
- base >= 4.7 && < 5
- vector >= 0.13 && < 0.14

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  dcpu16:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dcpu16-emulator-hs

tests:
  dcpu16-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dcpu16-emulator-hs
